### ISSUE TITLE
Submodule listing files

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm-ls-git#19]
If a git repo has submodules, `helm-ls-git` won't be able to find files inside the submodules. I understand that the submodules are not part of the current git repo, but is it possible to make `helm-ls-git` to identify submodules and search for files inside it?

**Comment by thierryvolpiatto** [comment]
The only thing needed to have submodules files listed is to add `--recurse-submodules` to `helm-ls-git-ls-switches`.
So I am closing this.
