### ISSUE TITLE
Use relative path from repository root.

### ISSUE THREAD

**Issue by proofit404** [emacs-helm/helm-ls-git#21]
Is there any way to use `app/models/user.rb` instead of `/path/to/project/app/models/user.rb`?

**Comment by jkp** [comment]
This doesn't seem to work any more: the problem seems to be that in [this commit](https://github.com/emacs-helm/helm-ls-git/commit/f756a93a08ecfca55a3b25794376a3f1189c5408) the call to `file-relative-name` was removed.

Is this an unintentional side-effect of that revert?
