### ISSUE TITLE
Git tag for stable melpa

### ISSUE THREAD

**Issue by ineu** [emacs-helm/helm-ls-git#26]
In addition to melpa there's now http://stable.melpa.org which build 'stable' versions of packages based on git tags ('releases'). Would you consider adding git tag to `helm-ls-git` to make it into melpa-stable? Thanks.

**Comment by thierryvolpiatto** [comment]
Eugene Diachkin <notifications@github.com> writes:

> In addition to melpa there's now http://stable.melpa.org which build 'stable' versions of packages based on git tags ('releases'). Would you consider adding git tag to helm-ls-git to make it into
> melpa-stable? Thanks.

Ok I will tag ASAP.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by kvaneesh** [comment]
Any update on this ?

**Comment by thierryvolpiatto** [comment]
Aneesh Kumar K.V <notifications@github.com> writes:

> Any update on this ?

Done, it have now the same tag number as the current helm version,
1.6.6.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
