### ISSUE TITLE
Feature request: C-u C-u C-s in helm-find-files should do git-grep if available

### ISSUE THREAD

**Issue by jwiegley** [emacs-helm/helm-ls-git#27]
This way C-u C-s is grep recursively, but C-u C-u C-s is grep throughout the entire project under version control.

**Comment by thierryvolpiatto** [comment]
John Wiegley <notifications@github.com> writes:

> This way C-u C-s is grep recursively, but C-u C-u C-s is grep
> throughout the entire project under version control.

Git grep is already accessible from helm-ls-git, which is accessible
from helm-find-files with C-d, it was not bound to a key but it is done
now.
So now from helm find-files:
C-d and C-s with one or two prefix arg should bring you to git grep.
(C-s alone grep one or marked files, C-u C-s to choose extensions, 
C-u C-u C-s to grep all)

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by jwiegley** [comment]
Great, thanks!
