### ISSUE TITLE
void function error in latest helm-ls-git 

### ISSUE THREAD

**Issue by darth10** [emacs-helm/helm-ls-git#28]
I'm getting this error after updating to the latest helm-ls-git version (`20140216.233`).
Any clue as to why it's happening?

```
Debugger entered--Lisp error: (void-function eieio-defclass-autoload)
  (eieio-defclass-autoload (quote helm-ls-git-source) (quote (helm-source-in-buffer)) "helm-ls-git" nil)
  eval-buffer(#<buffer  *load*> nil "c:/Users/awali/.emacs.d/elpa/helm-ls-git-20150216.233/helm-ls-git-autoloads.el" nil t)  ; Reading at buffer position 355
  load-with-code-conversion("c:/Users/awali/.emacs.d/elpa/helm-ls-git-20150216.233/helm-ls-git-autoloads.el" "c:/Users/awali/.emacs.d/elpa/helm-ls-git-20150216.233/helm-ls-git-autoloads.el" nil t)
  load("c:/Users/awali/.emacs.d/elpa/helm-ls-git-20150216.233/helm-ls-git-autoloads" nil t)
  package-activate-1(helm-ls-git [(20150216 233) ((helm (1 5))) "list git files."])
  package-activate(helm-ls-git (20150216 233))
  package-initialize()
```

**Comment by thierryvolpiatto** [comment]
Akhil Wali <notifications@github.com> writes:

> I'm getting this error after updating to the latest helm-ls-git version.
> Any clue as to why it's happening?

Compile with the emacs version you are using.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by darth10** [comment]
I'm using Emacs 24.3.1. Compiling the package files doesn't seem to solve the error.

**Comment by thierryvolpiatto** [comment]
Akhil Wali <notifications@github.com> writes:

> I'm using Emacs 24.3.1. Compiling the package files doesn't seem to solve the error.

Did you use another emacs version recently?

You should reinstall helm package completely, i.e delete it and
reinstall it, same for all helm files you have, helm-ls-git.el and all.

I could reproduce your error switching to emacs-24.3, after deleting the
helm-autoloads.el file and running again make (i.e recompiling) the error disappeared.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by darth10** [comment]
Tried that as well. Doesn't seem to fix it. 
Here are the helm packages I'm currently using.

```
helm-20150222.2156
helm-git-20120630.1403
helm-ls-git-20150216.233
```

**Comment by thierryvolpiatto** [comment]
Akhil Wali <notifications@github.com> writes:

> Tried that as well. Doesn't seem to fix it.

Please have a look at the FAQ on helm wiki, you have to remove all your
*.elc files, something went wrong in your installation.

> Here are the helm packages I'm currently using.
>
> helm-20150222.2156
> helm-git-20120630.1403

Why are you using this? Use only helm-ls-git.

> helm-ls-git-20150216.233
>
> —
> Reply to this email directly or view it on GitHub.*

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by darth10** [comment]
Seems fine now after reinstallation :smile: Closes #28.

**Comment by leemorgan-mobile** [comment]
I have this issue too. Tried reinstalling as per helm FAQ but the problem persists. Any other ideas?

```
24.3.1 ubuntu 14
installed from melpa...
  helm               20150227.225 installed  Helm is an Emacs incremental and narrowing framework
  helm-c-moccur      20150213.... installed  helm source for color-moccur.el
  helm-company       20140920.108 installed  Helm interface for company-mode
  helm-flycheck      20140915.752 installed  Show flycheck errors with helm
  helm-gtags         20150216.708 installed  GNU GLOBAL helm interface
  helm-ls-git        20150216.233 installed  list git files.
  helm-projectile    20150222.312 installed  Helm integration for Projectile
  helm-projectile... 20140429.952 installed  Find files in all projectile projects using helm
  helm-swoop         20150209.806 installed  Efficiently hopping squeezed lines powered by helm interface
```

```
Debugger entered--Lisp error: (void-function eieio-defclass-autoload)
  (eieio-defclass-autoload (quote helm-ls-git-source) (quote (helm-source-in-buffer)) "helm-ls-git" nil)
  eval-buffer(#<buffer  *load*-535663> nil "/home/local/.emacs.d/elpa/helm-ls-git-20150216.233/helm-ls-git-autoloads.el" nil t)  ; Reading at buffer position 364
  load-with-code-conversion("/home/local/.emacs.d/elpa/helm-ls-git-20150216.233/helm-ls-git-autoloads.el" "/home/local/.emacs.d/elpa/helm-ls-git-20150216.233/helm-ls-git-autoloads.el" nil t)
  load("/home/local/.emacs.d/elpa/helm-ls-git-20150216.233/helm-ls-git-autoloads" nil t)
  package-activate-1(helm-ls-git [(20150216 233) ((helm (1 5))) "list git files."])
  package-activate(helm-ls-git (20150216 233))
  package-initialize()
  eval-buffer(#<buffer  *load*-385375> nil "/home/local/.emacs.d/emacs.el" nil t)  ; Reading at buffer position 885
  load-with-code-conversion("/home/local/.emacs.d/emacs.el" "/home/local/.emacs.d/emacs.el" nil nil)
  load("/home/local/.emacs.d/emacs.el" nil nil t)
  load-file("/home/local/.emacs.d/emacs.el")
  org-babel-load-file("/home/local/.emacs.d/emacs.org")
  mapc(org-babel-load-file ("/home/local/.emacs.d/emacs.org"))
  eval-buffer(#<buffer  *load*> nil "/home/local/.emacs.d/init.el" nil t)  ; Reading at buffer position 1007
  load-with-code-conversion("/home/local/.emacs.d/init.el" "/home/local/.emacs.d/init.el" t t)
  load("/home/local/.emacs.d/init" t t)
  #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()

```

**Comment by thierryvolpiatto** [comment]
leemorgan-mobile <notifications@github.com> writes:

> I have this issue too. Tried reinstalling as per helm FAQ but the problem persists. Any other ideas?

Please clean your installation of differents helm packages, you have
deprecated packages, duplicated packages and unsupported packages.
Also for helm and helm-ls-git, you are still using old autoloads file...

Uninstall all your helm packages and reinstall one by one starting by
helm itself, then helm-ls-git and merely others after.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by darth10** [comment]
The error was not happening again after completely deleting my `elpa/`
folder and re-installing all my packages. YMMV.

On Fri, Feb 27, 2015 at 7:29 AM, Thierry Volpiatto <notifications@github.com
> wrote:

>
> leemorgan-mobile <notifications@github.com> writes:
>
> > I have this issue too. Tried reinstalling as per helm FAQ but the
> problem persists. Any other ideas?
>
> Please clean your installation of differents helm packages, you have
> deprecated packages, duplicated packages and unsupported packages.
> Also for helm and helm-ls-git, you are still using old autoloads file...
>
> Uninstall all your helm packages and reinstall one by one starting by
> helm itself, then helm-ls-git and merely others after.
>
> --
> Thierry
> Get my Gnupg key:
> gpg --keyserver pgp.mit.edu --recv-keys 59F29997
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emacs-helm/helm-ls-git/issues/28#issuecomment-76387530>
> .
>



-- 
Akhil Wali

# http://github.com/darth10 <https://github.com/darth10>
# http://darth10.github.com

**Comment by leemorgan-mobile** [comment]
"...you have
deprecated packages, duplicated packages and unsupported packages."

How can I tell?

the entire elpa?!....  :'(  :'(   :'( 

ok thanks - I'll try when I can face it.
