### ISSUE TITLE
keep buffer split as it was 

### ISSUE THREAD

**Issue by pcompassion** [emacs-helm/helm-ls-git#35]
I mainly use two buffers split vertically.

When I'm on the left buffer, and do helm-ls-git-ls, file list shows on the right buffer.

When I'm on the right buffer and do helm-ls-git-ls, buffer splits horizontally, and file list shows on the bottom buffer. (previous versions used the right buffer in this situation)

How do I force helm-ls-git to use either left or right buffer instead of splitting window horizontally?

**Comment by xuchunyang** [comment]
Try
```elisp
(setq helm-split-window-default-side 'other)
```
and don't customize other helm window related options.

**Comment by pcompassion** [comment]
Thanks!
