### ISSUE TITLE
Customize sources in helm-ls-git-ls?

### ISSUE THREAD

**Issue by xuchunyang** [emacs-helm/helm-ls-git#37]
`helm-ls-git-ls` is very slow in most git repos on my computer, it is feeding three sources, but only the `helm-source-ls-git` source is really necessary for me, for now, I just comment out code for the rest two. Could you please add a user custom option, maybe something like:

```elisp
(defcustom helm-ls-git-default-sources '(helm-source-ls-git-status
                                         helm-source-ls-git
                                         helm-source-ls-git-buffers)
  ...)
```

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> helm-ls-git-ls is very slow in most git repos on my computer, it is
> feeding three sources, but only the helm-source-ls-git source is
> really necessary for me, for now, I just comment out code for the rest
> two. Could you please add a user custom option, maybe something like:
>
> (defcustom helm-ls-git-default-sources '(helm-source-ls-git-status
>                                          helm-source-ls-git
>                                          helm-source-ls-git-buffers)
>   ...)

The 2 other sources have no impact on speed IMO, what is slow is the
first run of ls git when git create cache, next calls are fast.

But yes I will add your defcustom ASAP.

-- 
Thierry

https://emacs-helm.github.io/helm/
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> But yes I will add your defcustom ASAP.

Done.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by xuchunyang** [comment]
Nice, a question: if I have `(setq helm-ls-git-default-sources '(helm-source-ls-git))`, and in the `helm-ls-git-ls` command

```elisp
(unless (and helm-source-ls-git-status
             helm-source-ls-git
             helm-source-ls-git-buffers)
  (setq helm-source-ls-git-status
        ...
        helm-source-ls-git
        ...
        helm-source-ls-git-buffers
        ...))
```

it seems `unless`'s condition will always be `nil`.

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> Nice, a question: if I have (setq helm-ls-git-default-sources
> '(helm-source-ls-git)), and in the helm-ls-git-ls command
> it seems unless's condition will always be nil.

Indeed, should be fixed now.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by xuchunyang** [comment]
Thank you, It works fine now.

BTW, `(cl-every 'symbol-value helm-ls-git-default-sources)` seems more readable for me.

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> Thank you, It works fine now.
>
> BTW, (cl-every 'symbol-value helm-ls-git-default-sources) seems more readable for me.

I rarely use those macros, I can't remember what they do, so it is not
more readable for me.

-- 
Thierry

https://emacs-helm.github.io/helm/
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by xuchunyang** [comment]
> The 2 other sources have no impact on speed IMO, what is slow is the
> first run of ls git when git create cache, next calls are fast.

I find it is because `helm-ls-git-header-name` is very slow on my machine (OSX, 1.4 GHz Intel Core i5, 4 GB 1600 MHz DDR3), takes 0.88 seconds every time, and it will run three time with the default three source:

```elisp
(measure-time (helm-ls-git-header-name "foo"))
=> "0.887062"
```

Can this function be improve for better performance?

---
P.S.
```elisp
(defmacro measure-time (&rest body)
  "Measure the time it takes to evaluate BODY."
  `(let ((time (current-time)))
     ,@body
     (message "%.06f" (float-time (time-since time)))))
```

**Comment by zovt** [comment]
Sorry to bump an old, closed issue, but I was looking for exactly this functionality (only show files tracked by git in the helm-git-ls-git function), but it wasn't apparent from the README that this variable could be customized. Maybe add some docs somewhere in README or otherwise?

**Comment by thierryvolpiatto** [comment]
zovt <notifications@github.com> writes:

> Sorry to bump an old, closed issue, but I was looking for exactly this
> functionality (only show files tracked by git in the helm-git-ls-git
> function), but it wasn't apparent from the README that this variable
> could be customized. Maybe add some docs somewhere in README or
> otherwise?

See `helm-ls-git-default-sources`.
You can access customization with C-h c from any helm source (see C-h
m), I didn't add the helm-ls-git group yet so C-h c should bring you for
now to helm group from where you can access *ls-git group (see group
links at eob).

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997
