### ISSUE TITLE
the open buffers in project should include not only file buffers, e.g., dired buffers, magit buffers?

### ISSUE THREAD

**Issue by xuchunyang** [emacs-helm/helm-ls-git#38]
The function to compute open buffers in project is `helm-browse-project-get-buffers` (in helm).

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> The function to compute open buffers in project is helm-browse-project-get-buffers (in helm).

Done.

Thanks.

-- 
Thierry

https://emacs-helm.github.io/helm/
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by xuchunyang** [comment]
Confirmed.  Thanks for your work.
