### ISSUE TITLE
Invalid slot name: helm-source-buffers

### ISSUE THREAD

**Issue by s9gf4ult** [emacs-helm/helm-ls-git#40]
I have just installed the last version of `helm-ls-git` at 8cddd84ee4361b9d21f800adbaeeacf72645ab62
and trying to use `helm-ls-git-ls` but getting an error: 

`eieio-default-superclass: Invalid slot name: "#<helm-source-buffers Buffers in git project>", :buffer-list`

`helm` is of version emacs-helm/helm@f97fea98e6b72c3f92a947c04ac81574d3c931a4

**Comment by s9gf4ult** [comment]
In stable versions everything works, sorry.

**Comment by thierryvolpiatto** [comment]
Alexey Uimanov <notifications@github.com> writes:

> In stable versions everything works, sorry.

In non stable version also, if helm is installed properly.

-- 
Thierry
https://emacs-helm.github.io/helm/
