### ISSUE TITLE
Hi, how can I use ack to search git repo?

### ISSUE THREAD

**Issue by cmal** [emacs-helm/helm-ls-git#43]
In your README, you say:
"Full integration of git-grep, allow also usage of helm-grep (you can use ack-grep instead of grep)."
Can I use helm-ls-git to search the git repo for files that contains some word?
Is this related to `helm-ls-git-grep`?
And by the way, how can I use ack and helm-ls-git-grep to search git repo?
Thanks!

**Comment by thierryvolpiatto** [comment]
Yu Zhao <notifications@github.com> writes:

> In your README, you say: "Full integration of git-grep, allow also
> usage of helm-grep (you can use ack-grep instead of grep)."  Can I use
> helm-ls-git to search the git repo for files that contains some word?
> Is this related to helm-ls-git-grep?  And by the way, how can I use
> ack and helm-ls-git-grep to search git repo?  Thanks!

Switch to the file source and (look in mode-line) hit `C-h m`.

--
Thierry

**Comment by cmal** [comment]
![image](https://cloud.githubusercontent.com/assets/1773318/19220457/f5711846-8e5f-11e6-98b5-1044a0191a62.png)
![image](https://cloud.githubusercontent.com/assets/1773318/19220464/149724d6-8e60-11e6-81f3-4ff82ea25f76.png)
Sorry, I didn't quite catch you. There is nothing about grep or ack.

**Comment by thierryvolpiatto** [comment]
While you are in the helm session, more exactly in the files source, hit C-h m:

![capture d ecran_2016-10-09_16-20-59](https://cloud.githubusercontent.com/assets/1533939/19221112/fca8dd7e-8e3c-11e6-8bb7-955ccf1b410e.png)

**Comment by thierryvolpiatto** [comment]
And if you have configured helm to use ack `C-s` will use ack-grep to grep your files.
See `helm-grep-default-command`.

**Comment by cmal** [comment]
Oh! There is a new world. Pretty clear. Thanks!
![image](https://cloud.githubusercontent.com/assets/1773318/19225505/6d40d4fe-8ed0-11e6-8051-524aa5a7f8e1.png)

**Comment by cmal** [comment]
I should first use C-x C-f to open a helm buffer, and then use M-g a / M-g g to run grep for searching.

> 66	;; Now the git-grep command is defined in helm-grep.el,
> …	
> 158	Switch to `helm-find-files' with `C-x C-f', navigate to your directory
> 159	and launch git-grep from there.
