### ISSUE TITLE
adding .gitignored file to the file list?

### ISSUE THREAD

**Issue by pcompassion** [emacs-helm/helm-ls-git#44]
Some files are .gitignored but I still like to find those files in my project.  

Can I add specific files to the list which helm-ls-git will find?

**Comment by thierryvolpiatto** [comment]
pcompassion <notifications@github.com> writes:

> Some files are .gitignored but I still like to find those files in my project.

So why are they .gitignored ?
IOW just remove them from .gitignore (or comment them) as long as needed.

> Can I add specific files to the list which helm-ls-git will find?

No, not for now.  I could make the git-ls-files switches configurable
though but I don't see in what it is useful for now.

-- 
Thierry

**Comment by pcompassion** [comment]
They are project settings files.  
We don't want to include those files in git.   
But we still need to find/modify them a lot.

**Comment by thierryvolpiatto** [comment]
pcompassion <notifications@github.com> writes:

> They are project settings files.
> We don't want to include those files in git.

You don't need to include them in git, they will appear in status
buffer, and also in the buffers list if you have an open buffer, A `C-x
C-f` on any of those file will allow you to switch to HFF and its
actions, and RET will allow editing the file.

-- 
Thierry

**Comment by pcompassion** [comment]
Suppose you have a setting file which has your credentials, db settings, etc.  
You don't want to git control the file.  
If it shows up in magit status buffer, one might add it to git repo by mistake, we don't want that and that's why we have it in .gitignore.  

C-x C-f is bound to helm-find-files . 
I wish I could C-x C-f and just type the name of the file to locate the file as I could do with helm-ls-git but I don't think I can.

**Comment by thierryvolpiatto** [comment]
pcompassion <notifications@github.com> writes:

> Suppose you have a setting file which has your credentials, db
> settings, etc.  You don't want to git control the file.  If it shows
> up in magit status buffer, one might add it to git repo by mistake, we
> don't want that and that's why we have it in .gitignore.

Ok I have added a toggle command bound to `C-c i`.
It is available from status and listing files source.

> C-x C-f is bound to helm-find-files .

Globally but not from helm, it is bound to `helm-quit-and-find-file`
which is available in all helm sources (except helm-find-files itself of
course).

> I wish I could C-x C-f and just type the name of the file to locate
> the file as I could do with helm-ls-git but I don't think I can.

Yes you can, except that the file may be located deeper than root dir.

--
Thierry

**Comment by littlehome-eugene** [comment]
Thank you!

**Comment by manuel-uberti** [comment]
@thierryvolpiatto chiming in quickly for just another huge "thank you", because `C-c i` is awesome. I was looking for a way to edit a Git-ignored `.envrc` in my projects with navigating to the root of the project every time. Fantastic.
