### ISSUE TITLE
helm-ls-git-show-abs-or-relative ignored with non-empty search pattern

### ISSUE THREAD

**Issue by rcj** [emacs-helm/helm-ls-git#45]
It seems as if `candidate-transformer` is ignored in the `helm-ls-git-source` as soon as a search pattern is entered. It is correct as long as no search pattern is entered.

`helm-ls-git-transformer` is still called and returns the expected cons, however it seems as if the DISPL part is ignored and the REAL part is always shown.

To reproduce:
```
$ emacs-helm.sh

(add-to-path 'load-path "~/.emacs.d/site-lisp/helm-ls-git")
(require 'helm-ls-git)
(setq helm-ls-git-show-abs-or-relative 'relative)
(helm-ls-git-ls)
```

Expected: Candidates in "Git files" should be displayed relative to the git repository

Actual: As long as no search pattern is entered, files are relative, as soon as files are filtered by a pattern, files are shown with absolute path

**Comment by thierryvolpiatto** [comment]
Thanks to catch this.

Robin Campbell Joy <notifications@github.com> writes:

> Expected: Candidates in "Git files" should be displayed relative to the git repository

Should be fixed by 61deb35.
Let me know if it is now working as expected.

Thanks.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by rcj** [comment]
Yes, this is now working as expected, thanks for the quick response.

Interestingly this is similar to what I tried, however it seems I misunderstood something in the documentation. I changed `helm-ls-git-transformer` to take the source and added it to `filtered-candidate-transformer` but without changing `helm-ls-git-init` or `candidate-transformer`. However, that didn't made any difference. I could see that it was called and returned the expected result, but still displayed the absolute part as soon as I started filtering.

I guess what I don't understand yet is why the change to `helm-ls-git-init` is required. My understanding is that `init` is called once to generate the list of candidates and `candidate-transformer` is also called once. `filtered-candidate-transformer` however is called each time the input pattern changed. Whatever is then returned by `candidate-transformer` or, if defined, `filtered-candidate-transformer` is then used for display and is independent of what `init` produced at the beginning.

**Comment by thierryvolpiatto** [comment]
Robin Campbell Joy <notifications@github.com> writes:

> Yes, this is now working as expected, thanks for the quick response.
>
> Interestingly this is similar to what I tried, however it seems I
> misunderstood something in the documentation. I changed
> helm-ls-git-transformer to take the source and added it to
> filtered-candidate-transformer but without changing helm-ls-git-init
> or candidate-transformer. However, that didn't made any difference. I
> could see that it was called and returned the expected result, but
> still displayed the absolute part as soon as I started filtering.

It is what I did too before modifying init as well.

> I guess what I don't understand yet is why the change to
> helm-ls-git-init is required.

Normally things work as you describe above, but in this special case we
have to start with a clean list of files from init, otherwise the
transformer is transforming what it has already transformed and so on.
Git is returning a list of relatives fnames, so no need to recompute the
candidates in this case (i.e calling file-relative-name on an already
relative name).

> My understanding is that init is called once to generate the list of
> candidates and candidate-transformer is also called
> once.

True.

> filtered-candidate-transformer however is called each time the input
> pattern changed.

True.

> Whatever is then returned by candidate-transformer or, if defined,
> filtered-candidate-transformer is then used for display and is
> independent of what init produced at the beginning.

Yes, it is why it transforms what it have already transformed and when
file-relative-name is enough confused it returns an absolute path.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by rcj** [comment]
Thanks for the explanation!
