### ISSUE TITLE
Chinese chars are not displayed properly in "Git files" section

### ISSUE THREAD

**Issue by uqix** [emacs-helm/helm-ls-git#52]
![image](https://user-images.githubusercontent.com/10142314/60391640-b12b2200-9b25-11e9-8054-9f62d21335ef.png)

**Comment by xuchunyang** [comment]
I can reproduce

**Comment by xuchunyang** [comment]
https://stackoverflow.com/questions/34549040/git-not-displaying-unicode-file-names solves the issue for me.

Your can `$ git config --global core.quotePath false` or

```elisp
(setq helm-ls-git-ls-switches
      (cdr (split-string
            "git -c core.quotePath=false ls-files --full-name --")))
```

**Comment by thierryvolpiatto** [comment]
@xuchunyang  Thanks for this, added to documentation.
