### ISSUE TITLE
void function helm-ls-git-commit-mode after commit 071b00

### ISSUE THREAD

**Issue by tommyjiang** [emacs-helm/helm-ls-git#67]
I use spacemacs and after I upgrade this package on melpa to the latest it reports

> void function helm-ls-git-commit-mode

Could you please help me with this? Thanks.

**Comment by thierryvolpiatto** [comment]
Tommy ***@***.***> writes:

> I use spacemacs and after I upgrade this package on melpa to the latest it reports
>
>     void function helm-ls-git-commit-mode
>    
> Could you please help me with this? Thanks.

Sorry but I know nothing about spacemacs and how it installs/upgrades
packages, I guess it is a problem with compilation so what you can do is
remove helm-ls-git and reinstall it.

Thanks.

-- 
Thierry

**Comment by tommyjiang** [comment]
> Tommy ***@***.***> writes:
> I use spacemacs and after I upgrade this package on melpa to the latest it reports void function helm-ls-git-commit-mode Could you please help me with this? Thanks.
> Sorry but I know nothing about spacemacs and how it installs/upgrades packages, I guess it is a problem with compilation so what you can do is remove helm-ls-git and reinstall it. Thanks.
> […](#)
> -- Thierry

Thanks for the reply, I will try.

**Comment by tommyjiang** [comment]
Add `(require 'helm-ls-git)` to my init file solved this.

**Comment by thierryvolpiatto** [comment]
Tommy ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> Add (require 'helm-ls-git) to my init file solved this.

If you have to do this there is a problem in your config or your usage
of helm-ls-git.
The starting point for helm-ls-git is M-x helm-browse-project or (not
advised) M-x helm-ls-git.
Usage of require defeat benefit of autoloading.

-- 
Thierry

**Comment by tommyjiang** [comment]
> Tommy ***@***.***> writes:
> 1. ( ) text/plain (*) text/html Add (require 'helm-ls-git) to my init file solved this.
> If you have to do this there is a problem in your config or your usage of helm-ls-git. The starting point for helm-ls-git is M-x helm-browse-project or (not advised) M-x helm-ls-git. Usage of require defeat benefit of autoloading.
> […](#)
> -- Thierry

Yes I'm afraid so. Maybe it is related to the spacemacs config.
